[versions]
minSdk = "28"
compileSdk = "34"
targetSdk = "34"
versionCode = "1"
versionName = "1.0"
jvmTarget = "1.8"
kotlinCompilerExtensionVersion = "1.5.9"


kotlin = "1.9.22"
android-application = "8.3.0"
androidx-appCompat = "1.6.1"
androidx-constraintlayout = "2.1.4"
androidx-navigation = "2.7.7"
androidx-fragment = "1.6.2"
androidx-lifecycle-runtime-compose = "2.7.0"
androidx-compose-material3 = "1.2.0"
junit = "4.13.2"
hiltAndroid = "2.50"
foundationAndroid = "1.6.2"
uiToolingPreviewAndroid = "1.6.2"
uiTooling = "1.6.2"
kspVersion = "1.9.22-1.0.17"
org-jetbrains-kotlin-jvm = "1.9.22"
coroutines-core = "1.7.3"
java-inject = "1"

[libraries]
androidx-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appCompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }

androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }

androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle-runtime-compose" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }

androidx-compose-material3 = { module = "androidx.compose.material3:material3-android", version.ref = "androidx-compose-material3" }

junit = { module = "junit:junit", version.ref = "junit" }
androidx-foundation-android = { group = "androidx.compose.foundation", name = "foundation-android", version.ref = "foundationAndroid" }
androidx-ui-tooling-preview-android = { group = "androidx.compose.ui", name = "ui-tooling-preview-android", version.ref = "uiToolingPreviewAndroid" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hiltAndroid" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines-core" }
java-inject = { module = "javax.inject:javax.inject", version.ref = "java-inject" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation" }

[plugins]
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
android-application = { id = "com.android.application", version.ref = "android-application" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin-jvm" }

